
model = "qwen3-235b-a22b-instruct-2507"
model_provider = "dashscope"

[model_providers.dashscope]
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
env_key = "OPENAI_API_KEY"
name = "DashScope (Chat)"
wire_api = "chat"


[profiles.chat]
model_provider = "dashscope"
